export type GovernanceCountry = {
  name: string;
  region: 'Africa' | 'Americas' | 'Asia' | 'Europe' | 'Oceania';
};

const africa: GovernanceCountry[] = [
  { name: 'Algeria', region: 'Africa' },
  { name: 'Angola', region: 'Africa' },
  { name: 'Benin', region: 'Africa' },
  { name: 'Botswana', region: 'Africa' },
  { name: 'Burkina Faso', region: 'Africa' },
  { name: 'Burundi', region: 'Africa' },
  { name: 'Cabo Verde', region: 'Africa' },
  { name: 'Cameroon', region: 'Africa' },
  { name: 'Central African Republic', region: 'Africa' },
  { name: 'Chad', region: 'Africa' },
  { name: 'Comoros', region: 'Africa' },
  { name: 'Côte d\'Ivoire', region: 'Africa' },
  { name: 'Democratic Republic of the Congo', region: 'Africa' },
  { name: 'Djibouti', region: 'Africa' },
  { name: 'Egypt', region: 'Africa' },
  { name: 'Equatorial Guinea', region: 'Africa' },
  { name: 'Eritrea', region: 'Africa' },
  { name: 'Eswatini', region: 'Africa' },
  { name: 'Ethiopia', region: 'Africa' },
  { name: 'Gabon', region: 'Africa' },
  { name: 'Gambia', region: 'Africa' },
  { name: 'Ghana', region: 'Africa' },
  { name: 'Guinea', region: 'Africa' },
  { name: 'Guinea-Bissau', region: 'Africa' },
  { name: 'Kenya', region: 'Africa' },
  { name: 'Lesotho', region: 'Africa' },
  { name: 'Liberia', region: 'Africa' },
  { name: 'Libya', region: 'Africa' },
  { name: 'Madagascar', region: 'Africa' },
  { name: 'Malawi', region: 'Africa' },
  { name: 'Mali', region: 'Africa' },
  { name: 'Mauritania', region: 'Africa' },
  { name: 'Mauritius', region: 'Africa' },
  { name: 'Morocco', region: 'Africa' },
  { name: 'Mozambique', region: 'Africa' },
  { name: 'Namibia', region: 'Africa' },
  { name: 'Niger', region: 'Africa' },
  { name: 'Nigeria', region: 'Africa' },
  { name: 'Republic of the Congo', region: 'Africa' },
  { name: 'Rwanda', region: 'Africa' },
  { name: 'São Tomé and Príncipe', region: 'Africa' },
  { name: 'Senegal', region: 'Africa' },
  { name: 'Seychelles', region: 'Africa' },
  { name: 'Sierra Leone', region: 'Africa' },
  { name: 'Somalia', region: 'Africa' },
  { name: 'South Africa', region: 'Africa' },
  { name: 'South Sudan', region: 'Africa' },
  { name: 'Sudan', region: 'Africa' },
  { name: 'Tanzania', region: 'Africa' },
  { name: 'Togo', region: 'Africa' },
  { name: 'Tunisia', region: 'Africa' },
  { name: 'Uganda', region: 'Africa' },
  { name: 'Zambia', region: 'Africa' },
  { name: 'Zimbabwe', region: 'Africa' },
];

const asia: GovernanceCountry[] = [
  { name: 'Afghanistan', region: 'Asia' },
  { name: 'Armenia', region: 'Asia' },
  { name: 'Azerbaijan', region: 'Asia' },
  { name: 'Bahrain', region: 'Asia' },
  { name: 'Bangladesh', region: 'Asia' },
  { name: 'Bhutan', region: 'Asia' },
  { name: 'Brunei', region: 'Asia' },
  { name: 'Cambodia', region: 'Asia' },
  { name: 'China', region: 'Asia' },
  { name: 'Georgia', region: 'Asia' },
  { name: 'India', region: 'Asia' },
  { name: 'Indonesia', region: 'Asia' },
  { name: 'Iran', region: 'Asia' },
  { name: 'Iraq', region: 'Asia' },
  { name: 'Israel', region: 'Asia' },
  { name: 'Japan', region: 'Asia' },
  { name: 'Jordan', region: 'Asia' },
  { name: 'Kazakhstan', region: 'Asia' },
  { name: 'Kuwait', region: 'Asia' },
  { name: 'Kyrgyzstan', region: 'Asia' },
  { name: 'Laos', region: 'Asia' },
  { name: 'Lebanon', region: 'Asia' },
  { name: 'Malaysia', region: 'Asia' },
  { name: 'Maldives', region: 'Asia' },
  { name: 'Mongolia', region: 'Asia' },
  { name: 'Myanmar', region: 'Asia' },
  { name: 'Nepal', region: 'Asia' },
  { name: 'North Korea', region: 'Asia' },
  { name: 'Oman', region: 'Asia' },
  { name: 'Pakistan', region: 'Asia' },
  { name: 'Philippines', region: 'Asia' },
  { name: 'Qatar', region: 'Asia' },
  { name: 'Saudi Arabia', region: 'Asia' },
  { name: 'Singapore', region: 'Asia' },
  { name: 'South Korea', region: 'Asia' },
  { name: 'Sri Lanka', region: 'Asia' },
  { name: 'State of Palestine', region: 'Asia' },
  { name: 'Syria', region: 'Asia' },
  { name: 'Tajikistan', region: 'Asia' },
  { name: 'Thailand', region: 'Asia' },
  { name: 'Timor-Leste', region: 'Asia' },
  { name: 'Turkey', region: 'Asia' },
  { name: 'Turkmenistan', region: 'Asia' },
  { name: 'United Arab Emirates', region: 'Asia' },
  { name: 'Uzbekistan', region: 'Asia' },
  { name: 'Vietnam', region: 'Asia' },
  { name: 'Yemen', region: 'Asia' },
  { name: 'Taiwan', region: 'Asia' },
];

const europe: GovernanceCountry[] = [
  { name: 'Albania', region: 'Europe' },
  { name: 'Andorra', region: 'Europe' },
  { name: 'Austria', region: 'Europe' },
  { name: 'Belarus', region: 'Europe' },
  { name: 'Belgium', region: 'Europe' },
  { name: 'Bosnia and Herzegovina', region: 'Europe' },
  { name: 'Bulgaria', region: 'Europe' },
  { name: 'Croatia', region: 'Europe' },
  { name: 'Cyprus', region: 'Europe' },
  { name: 'Czechia', region: 'Europe' },
  { name: 'Denmark', region: 'Europe' },
  { name: 'Estonia', region: 'Europe' },
  { name: 'Finland', region: 'Europe' },
  { name: 'France', region: 'Europe' },
  { name: 'Germany', region: 'Europe' },
  { name: 'Greece', region: 'Europe' },
  { name: 'Hungary', region: 'Europe' },
  { name: 'Iceland', region: 'Europe' },
  { name: 'Ireland', region: 'Europe' },
  { name: 'Italy', region: 'Europe' },
  { name: 'Latvia', region: 'Europe' },
  { name: 'Liechtenstein', region: 'Europe' },
  { name: 'Lithuania', region: 'Europe' },
  { name: 'Luxembourg', region: 'Europe' },
  { name: 'Malta', region: 'Europe' },
  { name: 'Moldova', region: 'Europe' },
  { name: 'Monaco', region: 'Europe' },
  { name: 'Montenegro', region: 'Europe' },
  { name: 'Netherlands', region: 'Europe' },
  { name: 'North Macedonia', region: 'Europe' },
  { name: 'Norway', region: 'Europe' },
  { name: 'Poland', region: 'Europe' },
  { name: 'Portugal', region: 'Europe' },
  { name: 'Romania', region: 'Europe' },
  { name: 'Russia', region: 'Europe' },
  { name: 'San Marino', region: 'Europe' },
  { name: 'Serbia', region: 'Europe' },
  { name: 'Slovakia', region: 'Europe' },
  { name: 'Slovenia', region: 'Europe' },
  { name: 'Spain', region: 'Europe' },
  { name: 'Sweden', region: 'Europe' },
  { name: 'Switzerland', region: 'Europe' },
  { name: 'Ukraine', region: 'Europe' },
  { name: 'United Kingdom', region: 'Europe' },
  { name: 'Vatican City', region: 'Europe' },
];

const americas: GovernanceCountry[] = [
  { name: 'Antigua and Barbuda', region: 'Americas' },
  { name: 'Argentina', region: 'Americas' },
  { name: 'Bahamas', region: 'Americas' },
  { name: 'Barbados', region: 'Americas' },
  { name: 'Belize', region: 'Americas' },
  { name: 'Bolivia', region: 'Americas' },
  { name: 'Brazil', region: 'Americas' },
  { name: 'Canada', region: 'Americas' },
  { name: 'Chile', region: 'Americas' },
  { name: 'Colombia', region: 'Americas' },
  { name: 'Costa Rica', region: 'Americas' },
  { name: 'Cuba', region: 'Americas' },
  { name: 'Dominica', region: 'Americas' },
  { name: 'Dominican Republic', region: 'Americas' },
  { name: 'Ecuador', region: 'Americas' },
  { name: 'El Salvador', region: 'Americas' },
  { name: 'Grenada', region: 'Americas' },
  { name: 'Guatemala', region: 'Americas' },
  { name: 'Guyana', region: 'Americas' },
  { name: 'Haiti', region: 'Americas' },
  { name: 'Honduras', region: 'Americas' },
  { name: 'Jamaica', region: 'Americas' },
  { name: 'Mexico', region: 'Americas' },
  { name: 'Nicaragua', region: 'Americas' },
  { name: 'Panama', region: 'Americas' },
  { name: 'Paraguay', region: 'Americas' },
  { name: 'Peru', region: 'Americas' },
  { name: 'Saint Kitts and Nevis', region: 'Americas' },
  { name: 'Saint Lucia', region: 'Americas' },
  { name: 'Saint Vincent and the Grenadines', region: 'Americas' },
  { name: 'Suriname', region: 'Americas' },
  { name: 'Trinidad and Tobago', region: 'Americas' },
  { name: 'United States', region: 'Americas' },
  { name: 'Uruguay', region: 'Americas' },
  { name: 'Venezuela', region: 'Americas' },
];

const oceania: GovernanceCountry[] = [
  { name: 'Australia', region: 'Oceania' },
  { name: 'Fiji', region: 'Oceania' },
  { name: 'Kiribati', region: 'Oceania' },
  { name: 'Marshall Islands', region: 'Oceania' },
  { name: 'Federated States of Micronesia', region: 'Oceania' },
  { name: 'Nauru', region: 'Oceania' },
  { name: 'New Zealand', region: 'Oceania' },
  { name: 'Palau', region: 'Oceania' },
  { name: 'Papua New Guinea', region: 'Oceania' },
  { name: 'Samoa', region: 'Oceania' },
  { name: 'Solomon Islands', region: 'Oceania' },
  { name: 'Tonga', region: 'Oceania' },
  { name: 'Tuvalu', region: 'Oceania' },
  { name: 'Vanuatu', region: 'Oceania' },
];

export const worldGovernanceCountries: GovernanceCountry[] = [...africa, ...asia, ...europe, ...americas, ...oceania].sort((a, b) =>
  a.name.localeCompare(b.name)
);
